version: '3'

services:
  todosDB:
    image: mysql:8.0.29
    container_name: blog_mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
